# Generated by Django 4.0.1 on 2022-02-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=500)),
                ('img', models.CharField(default=0, max_length=500, null=True)),
                ('desc', models.URLField(default=0, null=True)),
            ],
        ),
    ]
