# Generated by Django 4.0.1 on 2022-02-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='desc',
            field=models.CharField(default=0, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='img',
            field=models.URLField(default=0, max_length=500, null=True),
        ),
    ]
