# Generated by Django 4.0.1 on 2022-02-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_data_desc_alter_data_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='img',
            field=models.URLField(default=0, max_length=5000, null=True),
        ),
    ]
