# Generated by Django 4.0.1 on 2022-02-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_data_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=500)),
                ('Last_Name', models.URLField(default=0, max_length=5000, null=True)),
                ('Email', models.URLField(default=0, max_length=5000, null=True)),
                ('Class_10_marks', models.IntegerField(default=0, null=True)),
                ('Class_12_marks', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
