# Generated by Django 4.0.1 on 2022-02-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_studentdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='Class_10_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='Class_12_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='Email',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='Last_Name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
